# Generated by Django 5.2.3 on 2025-07-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='dispute_note',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='exported_to_accounting',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_disputed',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='calculated_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
