# Generated by Django 5.2.3 on 2025-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_payroll_dispute_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='calculated_salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
