# Generated by Django 5.2.4 on 2025-07-23 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of attendance (auto-filled)')),
                ('clock_in', models.TimeField(blank=True, help_text='Time when the user clocked in', null=True)),
                ('clock_out', models.TimeField(blank=True, help_text='Time when the user clocked out', null=True)),
                ('gps_proof', models.ImageField(blank=True, help_text='Uploaded image of GPS map for location proof', null=True, upload_to='attendance_proofs/')),
                ('is_overtime', models.BooleanField(default=False, help_text='Indicates whether the employee worked overtime')),
                ('user', models.ForeignKey(help_text='User who is marking attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
    ]
