# Generated by Django 5.2.4 on 2025-07-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='gps_proof',
        ),
    ]
